Improve support for large job matrix (#21)
Co-authored-by: Penelope Yong <penelopeysm@gmail.com>

diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -7,8 +7,8 @@ on:
       - ".github/workflows/integration-tests.yaml"
 
 jobs:
-  setup-simple:
-    name: Setup Simple
+  exec-simple:
+    name: Execute Simple
     runs-on: ubuntu-latest
     permissions:
       actions: read
@@ -26,7 +26,7 @@ jobs:
       # Slow down on job to ensure that this is the last run
       - if: ${{ strategy.job-index == 0 }}
         run: sleep 5
-      # Keep `id` the same between `setup-simple` and `setup-complex`
+      # Keep `id` the same between `exec-simple` and `exec-complex`
       # to ensure we can separate output per job.
       - uses: ./
         id: matrix-output
@@ -37,7 +37,7 @@ jobs:
 
   test-simple:
     name: Test Simple
-    needs: setup-simple
+    needs: exec-simple
     runs-on: ubuntu-latest
     steps:
       - name: Output JSON
@@ -49,7 +49,7 @@ jobs:
               exit 1
           fi
         env:
-          output_json: ${{ needs.setup-simple.outputs.results-json }}
+          output_json: ${{ needs.exec-simple.outputs.results-json }}
           expected_json: |-
             [
               {
@@ -60,8 +60,8 @@ jobs:
               }
             ]
 
-  setup-complex:
-    name: Setup Complex
+  exec-complex:
+    name: Execute Complex
     runs-on: ubuntu-latest
     permissions:
       actions: read
@@ -81,7 +81,7 @@ jobs:
       results-json: ${{ steps.matrix-output.outputs.json }}
     steps:
       - uses: actions/checkout@v6
-      # Keep `id` the same between `setup-simple` and `setup-complex`
+      # Keep `id` the same between `exec-simple` and `exec-complex`
       # to ensure we can separate output per job.
       - uses: ./
         id: matrix-output
@@ -95,7 +95,7 @@ jobs:
 
   test-complex:
     name: Test Complex
-    needs: setup-complex
+    needs: exec-complex
     runs-on: ubuntu-latest
     steps:
       - name: Output JSON
@@ -107,7 +107,7 @@ jobs:
               exit 1
           fi
         env:
-          output_json: ${{ needs.setup-complex.outputs.results-json }}
+          output_json: ${{ needs.exec-complex.outputs.results-json }}
           expected_json: |-
             [
               {
@@ -183,8 +183,8 @@ jobs:
           echo "matrix-output2: ${{ steps.matrix-output2.outcome }}" >&2
           exit 1
 
-  setup-race-condition:
-    name: Setup Race Condition
+  exec-race-condition:
+    name: Execute Race Condition
     runs-on: ubuntu-latest
     permissions:
       actions: read
@@ -212,7 +212,7 @@ jobs:
 
   test-race-condition:
     name: Test Race Condition
-    needs: setup-race-condition
+    needs: exec-race-condition
     runs-on: ubuntu-latest
     steps:
       - name: Output JSON
@@ -224,7 +224,7 @@ jobs:
               exit 1
           fi
         env:
-          output_json: ${{ needs.setup-race-condition.outputs.results-json }}
+          output_json: ${{ needs.exec-race-condition.outputs.results-json }}
           expected_json: |-
             [
               {
@@ -234,3 +234,94 @@ jobs:
                 "index": 2
               }
             ]
+
+  # Workflow which contain a large number of jobs may run into "bash: Argument list too long"
+  # if we haven't reduced the job content internally. If this occurs failures may also occur
+  # on other integration tests.
+  #
+  # Having the number of jobs exceed 100 forces pagination to occur which takes some special
+  # handling
+  setup-large:
+    name: Setup Large
+    runs-on: ubuntu-latest
+    permissions: {}
+    outputs:
+      matrix-json: ${{ steps.matrix.outputs.json }}
+    steps:
+      - id: matrix
+        run: |
+          matrix='{"job": []}'
+          # Maximum allowed number of jobs is 256:
+          # "Strategy for job 'exec-large' produced N configurations which exceeds the maximum of 256 configurations"
+          #
+          # We choose the number 101 here to ensure we at least over 100 jobs which ensures
+          # that any queries targeting this workflow run must use pagination.
+          for i in {1..101}; do
+            # Include a UUID to artificially increase the job name length
+            uuid="$(cat /proc/sys/kernel/random/uuid)"
+            matrix="$(
+              jq \
+              --argjson index "$i" \
+              --arg uuid "${uuid}" \
+              '.job += [{index: $index, uuid: $uuid}]' \
+              <<<"${matrix}"
+            )"
+          done
+
+          {
+            echo "json<<EOF"
+            jq '.' <<<"${matrix}"
+            echo "EOF"
+          } | tee -a "$GITHUB_OUTPUT"
+
+  exec-large:
+    name: Execute Large (${{ matrix.job.index }}, ${{ matrix.job.uuid }})
+    needs: setup-large
+    runs-on: ubuntu-latest
+    permissions:
+      actions: read
+      contents: read
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJSON(needs.setup-large.outputs.matrix-json) }}
+    outputs:
+      results-json: ${{ steps.matrix-output.outputs.json }}
+    steps:
+      - uses: actions/checkout@v6
+      - uses: ./
+        id: matrix-output
+        with:
+          yaml: |
+            index: ${{ matrix.job.index }}
+            uuid: ${{ matrix.job.uuid }}
+          debug: true
+
+  test-large:
+    name: Test Large
+    needs:
+      - setup-large
+      - exec-large
+    runs-on: ubuntu-latest
+    steps:
+      - name: Expected JSON
+        id: expected
+        run: |
+          json="$(jq '.job | map({index, uuid})' <<<"${matrix}")"
+          {
+            echo "json<<EOF"
+            jq '.' <<<"${json}"
+            echo "EOF"
+          } >>"$GITHUB_OUTPUT"
+        env:
+          matrix: ${{ needs.setup-large.outputs.matrix-json }}
+      - name: Output JSON
+        run: |
+          if [[ "${output_json}" != "${expected_json}" ]]; then
+              cat <<<"${output_json}" >"output"
+              cat <<<"${expected_json}" >"expected"
+              diff output expected | cat -te
+              exit 1
+          fi
+        env:
+          output_json: ${{ needs.exec-large.outputs.results-json }}
+          expected_json: ${{ steps.expected.outputs.json}}
diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -26,19 +26,20 @@ runs:
   using: composite
   steps:
     - id: job
-      uses: beacon-biosignals/job-context@656c4f5d624c5e6b5679e742c179f5f6da90b02d  # v1.1.1
+      uses: beacon-biosignals/job-context@1978ffa0bc81154fe858102906001ff649a11282 # v1.1.3
     - name: Generate job output
       shell: bash
       run: |
         input_json="$(yq -o=json <<<"${input_yaml:?}")"
         jq -ne \
-            --argjson metadata "{\"job-id\": ${self_job_id:?}}" \
+            --argjson metadata "{\"job-id\": ${self_job_id:?}, \"job-index\": ${self_job_index:?}}" \
             --argjson outputs "${input_json:?}" \
             '$ARGS.named' | tee -a job-output.json
         touch job-sync
       env:
         input_yaml: ${{ inputs.yaml }}
         self_job_id: ${{ steps.job.outputs.id }}
+        self_job_index: ${{ strategy.job-index }}
     - name: Upload job output
       uses: actions/upload-artifact@v5
       with:
@@ -57,7 +58,7 @@ runs:
       run: |
         # Determine artifact jobs
         shopt -s globstar
-        jobs="$(jq -rs '[.[].metadata."job-id"] | to_entries | map({id: .value, index: .key})' matrix-output/**/*.json)"
+        jobs="$(jq -rs '[.[].metadata] | map({id: ."job-id", index: ."job-index"})' matrix-output/**/*.json)"
 
         if [[ "$RUNNER_DEBUG" -eq 1 ]] || [[ "${{ inputs.debug }}" == "true" ]]; then
             echo "Artifact jobs:" >&2
@@ -92,7 +93,7 @@ runs:
         # here as it has proven to be unreliable and does not include running jobs.
         jobs='[]'
         for attempt in $(seq 1 ${run_attempt}); do
-            attempt_jobs="$(gh api -X GET --paginate "/repos/{owner}/{repo}/actions/runs/${run_id:?}/attempts/${attempt:?}/jobs" --jq '.jobs')"
+            attempt_jobs="$(gh api -X GET --paginate "/repos/{owner}/{repo}/actions/runs/${run_id:?}/attempts/${attempt:?}/jobs" | jq -s '[.[].jobs[]]')"
 
             # Remove job entries which weren't actually executed during this attempt.
             # The GitHub API includes new `job_id`s for each `run_attempt` and we want to
@@ -105,9 +106,13 @@ runs:
         # Remove older jobs which were re-run
         jobs="$(jq 'sort_by(.created_at) | reverse | unique_by(.name)' <<<"${jobs}")"
 
+        # Reduce size of executed jobs content. Doing this avoids having `bash` fail with
+        # "Argument list too long" when the run contains 50+ jobs.
+        jobs="$(jq '[.[] | {id, name, run_id, run_attempt, created_at, completed_at, conclusion}]' <<<"${jobs}")"
+
         if [[ "$RUNNER_DEBUG" -eq 1 ]] || [[ "${{ inputs.debug }}" == "true" ]]; then
             echo "Executed jobs:" >&2
-            jq '[.[] | {id, name, run_id, run_attempt, created_at, completed_at, conclusion}]' <<<"${jobs}" >&2
+            jq '.' <<<"${jobs}" >&2
         fi
 
         {
@@ -180,9 +185,9 @@ runs:
             sync_artifact_name="${sync_artifact_prefix:?}-${job_index:?}"
 
             # https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#list-workflow-run-artifacts
-            artifacts="$(gh api -X GET "/repos/{owner}/{repo}/actions/runs/${run_id:?}/artifacts")"
+            artifacts="$(gh api -X GET --paginate "/repos/{owner}/{repo}/actions/runs/${run_id:?}/artifacts" | jq -s '[.[].artifacts[]]')"
 
-            sync_artifact_exists="$(jq --arg name "${sync_artifact_name:?}" '.artifacts | map(select(.name == $name)) | any' <<<"${artifacts}")"
+            sync_artifact_exists="$(jq --arg name "${sync_artifact_name:?}" 'map(select(.name == $name)) | any' <<<"${artifacts}")"
             if [[ "${sync_artifact_exists}" == "true" ]]; then
                 remaining_job_ids=("${remaining_job_ids[@]:1}")  # Drop the first element
                 continue
@@ -219,6 +224,6 @@ runs:
         # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
         {
             echo "json<<EOF"
-            jq -s '[.[].outputs]' matrix-output/**/*.json
+            jq -s 'sort_by(.metadata."job-index") | [.[].outputs]' matrix-output/**/*.json
             echo "EOF"
         } | tee -a "$GITHUB_OUTPUT"
